# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy -compat=1.17
builds:
  - env:
      - CGO_ENABLED=0
    ldflags: 
      - '-s -w -X github.com/mmiranda/markdown-index/cmd.version={{.Version}} -X github.com/mmiranda/markdown-index/cmd.commit={{.Commit}} -X github.com/mmiranda/markdown-index/cmd.date={{.Date}}'
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    image_templates:
      - "ghcr.io/mmiranda/markdown-index:latest"
      - "ghcr.io/mmiranda/markdown-index:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
    - "--label=org.opencontainers.image.source=https://github.com/mmiranda/markdown-index"
    - "--label=org.opencontainers.image.description=Tool to generate a global Markdown Summary Index based on other markdown files"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"    

# Publish on Homebrew Tap
brews:
  -
    name: markdown-index
    tap:
      owner: mmiranda
      name: homebrew-mdindex
      branch: main

    commit_author:
      name: Mateus Miranda
      email: mateusmiranda@gmail.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula

    homepage: "https://github.com/mmiranda/markdown-index"
    description: "Tool to generate a global Markdown Summary Index based on other markdown files"
    license: "MIT"

    test: |
      system "#{bin}/program", "version"
