package markdown

import (
	"bufio"
	"bytes"
	"io/ioutil"
	"log"
	"os"
	"path"
	"path/filepath"
	"strings"

	mdrender "github.com/Kunde21/markdownfmt/v2/markdown"
	toc "github.com/abhinav/goldmark-toc"
	"github.com/yuin/goldmark"
	meta "github.com/yuin/goldmark-meta"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/text"
)

var ignoreDirectories []string

//AbstractParagraph represents the paragraph which will be used as abstract.
type AbstractParagraph struct {
	title   string
	content string
}

type RawMarkdown struct {
	path    string
	content []byte
}

type AstNode struct {
	ast.Node
}

func Execute(output string, directory string) {

	// Add Cobra CLI later
	contentNode, contentByte := buildIndexContent(directory, ignoreDirectories)

	createMDFile(directory+"/"+output, contentNode.renderPlainMarkdown(contentByte), true)
}

// findFiles looks for files recursively
func findFiles(root string, ignoreDirectories []string) []*RawMarkdown {
	var files []*RawMarkdown

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		// Ignoring pre-defined directories and files that are not .md
		if filepath.Ext(path) != ".md" || contains(ignoreDirectories, filepath.Base(filepath.Dir(path))) {
			return nil
		}

		file := newMarkdownFile(path)

		if file.isFileAutoGenerated() {
			return nil
		}

		files = append(files, file)
		return nil
	})

	if err != nil {
		panic(err)
	}
	return files
}

func newMarkdownFile(path string) *RawMarkdown {
	var file RawMarkdown
	file.path = path
	return &file
}

// contains verify if a string is inside a set of strings
func contains(slice []string, searchterm string) bool {
	for _, value := range slice {
		if value == searchterm {
			return true
		}
	}
	return false
}

// calculatePathDepth returns the depth of a folder structure
func (md RawMarkdown) calculatePathDepth() int {
	return strings.Count(path.Dir(path.Clean("/"+md.path)), "/")
}

// readFile Reads a markdown file and return its content
func (file RawMarkdown) readFile() []byte {
	content, err := ioutil.ReadFile(file.path)

	if err != nil {
		log.Fatalf("Error opening file %s!", file.path)
	}

	return content

}

// FirstParagraph gets the text of first paragraph in a markdown file
func (md RawMarkdown) getMetadata() map[string]interface{} {
	source := md.readFile()

	var buf bytes.Buffer
	markdown := goldmark.New(
		goldmark.WithExtensions(
			meta.Meta,
		),
	)

	context := parser.NewContext()
	if err := markdown.Convert([]byte(source), &buf, parser.WithContext(context)); err != nil {
		panic(err)
	}

	return meta.Get(context)
}

func (md *RawMarkdown) addMetadata() {
	metadata := "---\nTitle: markdown-index\n---\n"

	currentString := string(md.content)
	md.content = []byte(metadata + currentString)
}

func (md RawMarkdown) isFileAutoGenerated() bool {
	metadata := md.getMetadata()
	if metadata != nil && metadata["Title"] == "markdown-index" {
		return true
	}

	return false
}

// FirstParagraph gets the text of first paragraph in a markdown file
func (md *RawMarkdown) FirstParagraph() AbstractParagraph {
	doc, source := md.ParseDocument()

	if paragraph := md.FilterHeadingAbstract("Abstract"); (paragraph != AbstractParagraph{}) {
		return AbstractParagraph{
			paragraph.title,
			paragraph.content,
		}
	}

	abstractContent := ""

	// identify single node documents aka markdown with a single heading/paragraph
	if doc.FirstChild() != doc.LastChild() {
		abstractContent = string(doc.FirstChild().NextSibling().Text(source))
	}

	return AbstractParagraph{
		string(doc.FirstChild().Text(source)),
		abstractContent,
	}
}

func (md *RawMarkdown) ParseDocument() (ast.Node, []byte) {
	source := md.readFile()
	gm := goldmark.New(
		goldmark.WithParserOptions(
			parser.WithASTTransformers(),
		),
		goldmark.WithExtensions(
			meta.Meta,
		),
	)

	return gm.Parser().Parse(text.NewReader(source)), source
}

func (md *RawMarkdown) FilterHeadingAbstract(title string) AbstractParagraph {
	var content AbstractParagraph

	doc, source := md.ParseDocument()

	err := ast.Walk(doc, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		s := ast.WalkStatus(ast.WalkContinue)
		var err error

		if n.Kind().String() == "Heading" && string(n.Text(source)) == title {
			content = AbstractParagraph{
				string(n.Text(source)),
				string(n.NextSibling().Text(source)),
			}
			s = ast.WalkStatus(ast.WalkStop)
		}
		return s, err
	})

	if err != nil {
		log.Fatalf("An error occured: %s", err)
	}

	return content
}
func deleteFile(file string) {
	if fi, err := os.Stat(file); err == nil {
		if fi.Mode().IsRegular() {
			err := os.Remove(file)
			if err != nil {
				panic("Test failed deleting file")
			}
		}
	}

}

func createMDFile(filePath, content string, metadata bool) {
	deleteFile(filePath)
	file, err := os.OpenFile(filePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)

	if err != nil {
		log.Fatalf("failed creating file: %s", err)
	}

	datawriter := bufio.NewWriter(file)
	if metadata {
		metadata := "---\nTitle: markdown-index\n---\n"
		content = metadata + content
	}

	datawriter.WriteString(content)

	datawriter.Flush()
	file.Close()
}

func buildIndexContent(sourcePath string, ignoreDirectories []string) (AstNode, []byte) {

	files := findFiles(sourcePath, ignoreDirectories)

	var finalDoc AstNode
	finalDoc.Node = ast.NewDocument()

	for _, file := range files {

		heading := ast.NewHeading(file.calculatePathDepth())

		paragraph := ast.NewParagraph()

		heading.AppendChild(heading, ast.NewString([]byte(file.FirstParagraph().title)))

		paragraphContent := file.FirstParagraph().content + "\n\n[Read more on the original file...](" + strings.TrimPrefix(file.path, "../") + ")"
		paragraph.AppendChild(paragraph, ast.NewString([]byte(paragraphContent)))

		finalDoc.AppendChild(finalDoc, heading)
		finalDoc.AppendChild(finalDoc, paragraph)

	}

	var markdown RawMarkdown
	markdown.content = []byte(finalDoc.renderPlainMarkdown([]byte("")))

	tocNode, source := markdown.buildTableOfContents()

	return tocNode, source
}

func (document AstNode) renderHTMLMarkdown(content []byte) string {
	var buffer bytes.Buffer

	gm := goldmark.New(
		goldmark.WithExtensions(
			meta.Meta,
		),
	)

	err := gm.Renderer().Render(&buffer, content, document.Node)

	if err != nil {
		log.Fatalf("An error occured: %s", err)
	}

	return buffer.String()
}

func (document AstNode) renderPlainMarkdown(content []byte) string {
	var buffer bytes.Buffer

	mdrender := mdrender.NewRenderer()
	err := mdrender.Render(&buffer, content, document.Node)
	if err != nil {
		log.Fatalf("An error occured: %s", err)
	}

	return buffer.String()
}

func (source RawMarkdown) buildTableOfContents() (AstNode, []byte) {
	gm := goldmark.New(
		goldmark.WithParserOptions(parser.WithAutoHeadingID()),
		goldmark.WithExtensions(
			&toc.Extender{},
			meta.Meta,
		),
	)

	return AstNode{gm.Parser().Parse(text.NewReader(source.content))}, source.content
}
